trigger:
- main

pool:
  name: Default
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: PackerBuild@1
  displayName: 'Packer build'
  inputs:
    targetType: 'inline'
    script: 'packer build '$(System.DefaultWorkingDirectory)/aws-ubuntu.pkr.hcl'

