trigger:
- main

variables:
  - group: ACCESS_KEYS

pool:
  name: Default
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
  echo "##vso[task.setvariable KEY_ID=AKIA3JZG6UMCDTGFRN7C"
  echo "##vso[task.setvariable KEY_ID=jrqNU7VGuFOnj1T+khHFmE2Ta0sdYvuOVJvwkjtm"
  packer build '$(System.DefaultWorkingDirectory)/aws-ubuntu.pkr.hcl'

- script: |
    echo 'Hello World!'
  displayName: 'test hello world'

