trigger:
- main

variables:
  - group: ACCESS_KEYS

pool:
  name: Default
  vmImage: ubuntu-latest

# Name: docker_init
# Description: Performs docker setup on the current agent
steps:
  # - task: DockerInstaller@0
  #   inputs:
  #     dockerVersion: '17.09.0-ce'


  # - task: Docker@2
  #   displayName: Docker login
  #   inputs:
  #     containerRegistry: $(CONTAINER_REGISTRY)
  #     command: 'login'

  - script: |
      echo $(AWS_ACCESS_KEY_ID)
      echo $(AWS_SECRET_ACCESS_KEY)

  - script: |
      export $(AWS_ACCESS_KEY_ID)
      export $(AWS_SECRET_ACCESS_KEY)
      pwd
      mv install_nginx.yml /$(System.DefaultWorkingDirectory)
      cd $(System.DefaultWorkingDirectory)
      pwd
      ls
      mv goss.yaml /home/ubuntu
      cd /home/ubuntu
      ls
      packer build '$(System.DefaultWorkingDirectory)/aws-ubuntu.pkr.hcl'
