# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: Default
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- script: |
    echo 'Hello World!'
  displayName: 'test hello world'

- bash: echo 'Hello Script World' >> HelloWorld.txt
- bash: ls
- task: CopyFiles@2
  inputs:
    Contents: 'HelloWorld.txt'
    targetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'text-file'

- script: cat '$(Build.ArtifactStagingDirectory)/HelloWorld.txt'


- task: DownloadBuildArtifacts@0
  displayName: downloading artifact
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'text-file'
    downloadPath: '$(System.ArtifactsDirectory)'

- bash: cat '$(System.ArtifactsDirectory)/HelloWorld.txt'
