trigger:
- main

pool:
  name: Default
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- script: |
    echo 'Hello World!'
  displayName: 'test hello world'

- script: |
    packer build aws-ubuntu.pkr.hcl