trigger:
- main

variables:
  - group: ACCESS_KEYS

pool:
  name: Default
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
     echo $(ACCESS_KEY_ID)
     echo $(SECRET_ACCESS_KEY)

# - script: |
#     packer build '$(System.DefaultWorkingDirectory)/aws-ubuntu.pkr.hcl'

# - script: |
#     echo 'Hello World!'
#   displayName: 'test hello world'
